const books = [
    {
      _id: '1',
      name: 'Algebra',
      image: '../../public/images/algebra.jpg',
      description:'Algebra Text Book',
      publisher: 'Waterloo',
      category: 'Book',
      price: 89.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '2',
      name: 'biology',
      image: '../../public/images/biology.jpg',
      description:'Biology Text Book',
      publisher: 'Apple',
      category: 'Book',
      price: 599.99,
      countInStock: 7,
      rating: 4.0,
      numReviews: 8,
    },
    {
      _id: '3',
      name: 'calculus',
      image: '../../public/images/calculus.jpg',
      description:'Calculus text book',
      publisher: 'Waterloo',
      category: 'Book',
      price: 929.99,
      countInStock: 5,
      rating: 3,
      numReviews: 12,
    },
    {
      _id: '4',
      name: 'chemistry',
      image: '../../public/images/chemistry.jpg',
      description:'Chemistry text book',
      publisher: 'Toronto',
      category: 'Book',
      price: 399.99,
      countInStock: 11,
      rating: 5,
      numReviews: 12,
    },
    {
      _id: '5',
      name: 'English',
      image: '../../public/images/english.jpg',
      description: 'English Book',
      publisher: 'London',
      category: 'Book',
      price: 49.99,
      countInStock: 7,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: '6',
      name: 'physics',
      image: '../../public/images/physics.jpg',
      description:'physics textbook',
      publisher: 'New York',
      category: 'Book',
      price: 29.99,
      countInStock: 0,
      rating: 4,
      numReviews: 12,
    },
  ]

  export default books